version: "3.8"

services:
  nginx-port1:
    image: nginx:latest
    container_name: nginx-port1
    # ini long sintax portsnya
    ports:
      - protocol: tcp
        published: 8080
        target: 80

  nginx-port2:
    image: nginx:latest
    container_name: nginx-port2
    # ini short sintax portsnya
    ports:
      - "8081:80"
